### ISSUE TITLE
Couldn't accces to the image 

### ISSUE THREAD

**Issue by dark-kali-lml** [fchmainy/nginx_k8s_apigw#2]
HI, I trying to use the apigw but when I applied the yaml, I've  got the following error:

Warning  Failed          77s (x3 over 117s)  kubelet            
**Failed to pull image "registry.gitlab.com/k8sfch/demo-name-generator/apigw:latest": rpc error: code = Unknown desc = Error response from daemon: Head "https://registry.gitlab.com/v2/k8sfch/demo-name-generator/apigw/manifests/latest": denied: access forbidden**
  Warning  Failed          77s (x3 over 117s)  kubelet            Error: ErrImagePull 
  
  could you help me please?

**Comment by fchmainy** [comment]
Hi,

i removed it plus it was on a private registry. You will have to re-build a new apigw there :)
sorry @dark-kali-lml 

be well.
Fouad
